### ISSUE TITLE
Pre-requirement in clean OS installations - README.md

### ISSUE THREAD

**Issue by vitor-diego-s** [WandersonAlves/generator-kube-microservice-node#7]
# Context
When running the generator in a new operating system environment it fails
looking for the 'git-init' generator.

![Screenshot from 2019-09-04 10-59-39](https://user-images.githubusercontent.com/15676011/64262812-0eb46400-cf05-11e9-88cb-a2663c11bc3e.png)
 
Running  ``` npm i -g yo generator-git-init ``` has fixed the issue. 

![Screenshot from 2019-09-04 11-02-20](https://user-images.githubusercontent.com/15676011/64262879-255abb00-cf05-11e9-92ef-65dbed7bf027.png)

**Comment by WandersonAlves** [comment]
Hi, thanks for notice that @diegofreemind !

I have a solution and i should release a new version soon

**Comment by WandersonAlves** [comment]
So, there was a bug. I was not using the local version of `generator-git-init`, please, give a new try on https://github.com/e3Labs/generator-kube-microservice-node/releases/tag/v2.3.8

**Comment by WandersonAlves** [comment]
@all-contributors please add @diegofreemind for bug, ideas
